---
- name: Install dependencies
  hosts: localhost
  tasks:
    - name: Global node packages
      block:
        - name: Add dotenv-cli
          community.general.pnpm:
            global: true
            name: dotenv-cli
        - name: Add pm2
          community.general.pnpm:
            global: true
            name: pm2
    - name: Install all js dependencies
      community.general.pnpm:
        path: "{{ ansible_env.HOME }}/origoshift"
- name: Build monorepo
  hosts: localhost
  tasks:
    - name: Generate prisma client
      ansible.builtin.command:
        argv:
          - pnpm
          - --filter
          - database
          - generate
      changed_when: true
    - name: Build database
      ansible.builtin.command: pnpm --filter database build
      changed_when: true
    - name: Build shared packages
      ansible.builtin.command:
        argv:
          - pnpm
          - --filter
          - "./packages/**"
          - -r
          - build
      changed_when: true
    - name: Build all the node projects
      ansible.builtin.command: pnpm -r build
      changed_when: true
